/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSchema {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  orderId: string;
  productId: string;
  status: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
  userId?: string;
}

export interface getSchema {
  orderId?: string;
  paymentId: string;
  productId?: string;
  status?: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
  version?: number;
}

export interface interfaceCreateSchema {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  orderId: string;
  productId: string;
  status: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
  userId: string;
}

export interface interfaceUpdateSchema {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  orderId?: string;
  paymentId: string;
  productId?: string;
  status?: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
  userId?: string;
}

export interface listAttachmentsSchema {}

export interface listEntitySchema {
  orderId?: string;
  productId?: string;
  status?: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
}

export interface outputEntitySchema {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  createdAt: string;
  createdBy?: string;
  latestVersion?: any;
  orderId: string;
  paymentId?: string;
  productId: string;
  status: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedAt: string;
  updatedBy: string;
  userId?: string;
  version: number;
}

export interface updateSchema {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  orderId?: string;
  paymentId?: string;
  productId?: string;
  status?: 'open' | 'pending' | 'authorized' | 'failed' | 'expired' | 'canceled' | 'paid';
  updatedBy?: string;
  userId?: string;
}
